# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    app.orm_purger:
        class: 'Doctrine\Common\DataFixtures\Purger\ORMPurger'

    Doctrine\Common\DataFixtures\Purger\ORMPurgerInterface: '@app.orm_purger'

    Gedmo\Translatable\TranslatableListener: '@stof_doctrine_extensions.listener.translatable'

    gedmo.listener.ip_traceable:
        class: Gedmo\IpTraceable\IpTraceableListener
        calls:
            - setAnnotationReader: ['@annotation_reader']
        tags: ['doctrine.event_subscriber']

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        calls:
            - setAnnotationReader: ['@annotation_reader']
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    App\EventSubscriber\IpTraceSubscriber:
        arguments:
            - '@gedmo.listener.ip_traceable'
        tags: ['kernel.event_subscriber']    
    
    Gedmo\Uploadable\UploadableListener: '@stof_doctrine_extensions.listener.uploadable'
    
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
